# Generated by Django 5.2.1 on 2025-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_calllog_options_rename_comment_calllog_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='created_at',
        ),
    ]
