# Generated by Django 5.2.1 on 2025-05-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_calllog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
