# Generated by Django 5.2.1 on 2025-05-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
