# Generated by Django 5.2.1 on 2025-05-13 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.company'),
        ),
    ]
