# Generated by Django 5.2.1 on 2025-05-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='company_name',
            new_name='company',
        ),
    ]
