# Generated by Django 5.2.1 on 2025-05-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_company_name_student_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
