# Generated by Django 5.2.1 on 2025-05-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_company_options_remove_company_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '企業', 'verbose_name_plural': '企業一覧'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生一覧'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='企業名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='after_special_notes',
            field=models.TextField(blank=True, null=True, verbose_name='TEL後特記事項'),
        ),
        migrations.AlterField(
            model_name='student',
            name='before_special_notes',
            field=models.TextField(blank=True, null=True, verbose_name='TEL前特記事項'),
        ),
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.company', verbose_name='企業名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学生ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='student',
            name='done_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wチェック済み'),
        ),
        migrations.AlterField(
            model_name='student',
            name='done_decline',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='辞退処理済み'),
        ),
        migrations.AlterField(
            model_name='student',
            name='done_draft',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wチェ必要'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学部'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call_date',
            field=models.DateField(blank=True, null=True, verbose_name='1コール目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call_notes',
            field=models.TextField(blank=True, null=True, verbose_name='1コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call_timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1コール目時間区分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='初回エントリー日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grad_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='卒年度'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大分類'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小分類'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='シメイ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='need_process',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='処理必要'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='process_destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TEL処理先'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_date',
            field=models.DateField(blank=True, null=True, verbose_name='2コール目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_notes',
            field=models.TextField(blank=True, null=True, verbose_name='3コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2コール目時間区分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_date',
            field=models.DateField(blank=True, null=True, verbose_name='2コール目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_notes',
            field=models.TextField(blank=True, null=True, verbose_name='3コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2コール目時間区分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大学'),
        ),
    ]
