# Generated by Django 5.2.1 on 2025-05-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_company_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_call_timezone',
            field=models.CharField(blank=True, choices=[('morning', '朝（9:00〜12:00）'), ('noon', '昼（12:00〜15:00）'), ('evening', '夕（15:00〜18:00）')], max_length=50, null=True, verbose_name='1コール目時間区分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_timezone',
            field=models.CharField(blank=True, choices=[('morning', '朝（9:00〜12:00）'), ('noon', '昼（12:00〜15:00）'), ('evening', '夕（15:00〜18:00）')], max_length=50, null=True, verbose_name='2コール目時間区分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_timezone',
            field=models.CharField(blank=True, choices=[('morning', '朝（9:00〜12:00）'), ('noon', '昼（12:00〜15:00）'), ('evening', '夕（15:00〜18:00）')], max_length=50, null=True, verbose_name='2コール目時間区分'),
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='大分類')),
                ('classification', models.CharField(blank=True, choices=[('immediately', '即TEL'), ('confirmation', '直確TEL')], max_length=100, null=True, verbose_name='プルダウン用分類')),
                ('talk_script', models.URLField(blank=True, null=True, verbose_name='トークスクリプトへのリンク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='students.company', verbose_name='企業名')),
            ],
            options={
                'verbose_name': 'パターン',
                'verbose_name_plural': 'パターン一覧',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='major_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.pattern', verbose_name='大分類'),
        ),
    ]
