# Generated by Django 5.2.1 on 2025-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_first_call_timezone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '全企業の学生一覧'},
        ),
        migrations.AddField(
            model_name='student',
            name='done_tel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='TEL終了'),
        ),
    ]
