# Generated by Django 5.2.1 on 2025-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_options_student_done_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='second_call_notes',
            field=models.TextField(blank=True, null=True, verbose_name='2コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_date',
            field=models.DateField(blank=True, null=True, verbose_name='3コール目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_timezone',
            field=models.CharField(blank=True, choices=[('morning', '朝（9:00〜12:00）'), ('noon', '昼（12:00〜15:00）'), ('evening', '夕（15:00〜18:00）')], max_length=50, null=True, verbose_name='3コール目時間区分'),
        ),
    ]
