# Generated by Django 5.2.1 on 2025-05-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_second_call_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大分類'),
        ),
    ]
