# Generated by Django 5.2.1 on 2025-05-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_student_major_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='major_class',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='talk_script',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_config', to='students.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_call_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_call_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2コール目結果'),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_call_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3コール目結果'),
        ),
        migrations.CreateModel(
            name='PatternItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_class', models.CharField(max_length=100, verbose_name='大分類')),
                ('classification', models.CharField(choices=[('immediately', '即TEL'), ('confirmation', '直確TEL')], max_length=100, verbose_name='分類')),
                ('talk_script', models.URLField(blank=True, null=True, verbose_name='トークスクリプトURL')),
                ('call_results', models.TextField(blank=True, null=True, verbose_name='想定されるコール結果（カンマ区切り）')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.pattern')),
            ],
        ),
    ]
