# Generated by Django 5.2.1 on 2025-05-14 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_pattern_options_remove_pattern_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類キー')),
                ('results', models.TextField(verbose_name='コール結果リスト（カンマ区切り）')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'verbose_name': 'パターン', 'verbose_name_plural': 'パターン一覧'},
        ),
        migrations.RemoveField(
            model_name='patternitem',
            name='call_results',
        ),
        migrations.AlterField(
            model_name='patternitem',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.callresult', verbose_name='分類'),
        ),
    ]
