# Generated by Django 5.2.1 on 2025-05-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_callresult_alter_pattern_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callresult',
            options={'verbose_name': 'コール結果', 'verbose_name_plural': 'コール結果一覧'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'エントリー', 'verbose_name_plural': 'エントリー一覧'},
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日時'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_config', to='students.company', verbose_name='企業名'),
        ),
    ]
