# Generated by Django 5.2.1 on 2025-05-16 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_version_alter_student_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='version',
        ),
        migrations.AddField(
            model_name='student',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ロック時刻'),
        ),
        migrations.AddField(
            model_name='student',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='編集中ユーザー'),
        ),
    ]
