# Generated by Django 5.2.1 on 2025-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_student_updated_at_remove_student_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='done_check',
        ),
        migrations.RemoveField(
            model_name='student',
            name='done_decline',
        ),
        migrations.AlterField(
            model_name='student',
            name='process_destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='初回エントリー経路'),
        ),
    ]
