# Generated by Django 5.2.1 on 2025-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_student_done_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='done_tel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='TEL終了/処理済'),
        ),
    ]
